import "./globals.css";
import Navigation from "@/components/Header/Navigation";
import Providers from "./lib";
 import { ToastContainer } from 'react-toastify';
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
        <Navigation />
         <ToastContainer />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
